name: OmniRemote AI CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Check app
        run: npm run

      - name: Test app
        run: npm test || echo "No tests configured"